# Travis CI configuration

# xenial (has build-essential) + Java
dist: xenial
# we are requiring VM instead of Docker builds due to sporadic nailgun test suite failures
sudo: required
language: java

jdk:
  - openjdk8
  - openjdk10
  - openjdk11

script: >
  true
# compile and run the test suite
# we manually set PRISM_JAVA to the java on the PATH as the python invocation of prism-auto fiddles with the PATH variable...  
#script: >
#    cd prism &&
#    make &&
#    echo 'Compilation successful, running test suite....' && echo &&
#    export PRISM_JAVA=`which java` &&
#    make tests &&
#    echo && echo 'Yay'

jobs:
  include:
    - stage: fulltest
      script: >
        curl -O 'http://search.maven.org/remotecontent?filepath=org/jacoco/jacoco/0.8.4/jacoco-0.8.4.zip' &&
        unzip -d jacoco-0.8.4 jacoco-0.8.4.zip &&
        export JACOCO_AGENT="`pwd`/jacoco-0.8.4/lib/jacocoagent.jar"
        cd prism &&
        export JACOCO_TARGET="`pwd`/jacoco.exec"
        make &&
        echo 'Compilation successful, running test suite....' && echo &&
        export PRISM_JAVA=`which java` &&
        export PRISM_JAVA_DEBUG="-javaagent:$JACOCO_AGENT=destfile=$JACOCO_TARGET"
        make testsfull &&
        echo && echo 'Yay' &&
        ls -la $JACOCO_TARGET

# notifications
notifications:
  email:
    recipients:
#      - d.a.parker@cs.bham.ac.uk
      - klein@tcs.inf.tu-dresden.de
    on_success: change
    on_failure: always
